Desktop/intership/InterWeb/InterWeb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('InterWebApp.urls', namespace = 'InterWebApp')),


]

Desktop/intership/InterWeb/InterWebApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView,patient_dashboard,doctor_dashboard,dashboard

app_name = 'InterWebApp'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path("dashboard/", dashboard, name="dashboard"),
    path("patient_dashboard/", patient_dashboard, name="patient_dashboard"),
    path("doctor_dashboard/", doctor_dashboard, name="doctor_dashboard"),

  
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/intership/InterWeb/InterWebApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


# class User(AbstractBaseUser):
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)
#     username = models.CharField(max_length=150, unique=True)
#     email = models.EmailField(unique=True)
#     user_type = models.CharField(choices=USER_TYPE_CHOICES, max_length=30)
#     profile_pic = models.ImageField(upload_to='profile_pics/', blank=True, null=True)

#     USERNAME_FIELD = 'username'

#     def __str__(self):
#         return self.username



class Address(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    line1 = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    pincode = models.CharField(max_length=6)
    
    def __str__(self):
        return self.line1


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username
    

class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    user_type = models.CharField(blank=False, max_length=30)

    
    def __str__(self):
        return self.user.username

Desktop/intership/InterWeb/InterWebApp/forms.py
# myproject/forms.py
from django import forms
from allauth.account.forms import SignupForm
from .models import Address,Profile,Doctor,Patient


USER_TYPE_CHOICES = (
        ('patient', 'Patient'),
        ('doctor', 'Doctor'),
    )

class CustomSignUpForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name',widget=forms.TextInput(attrs={
        'placeholder': 'subrat',}))
    last_name = forms.CharField(max_length=30, label='Last Name',widget=forms.TextInput(attrs={
        'placeholder': 'singh',}))
    profile_pic = forms.ImageField(label='Profile Picture',required=False)
    user_type = forms.ChoiceField(choices=USER_TYPE_CHOICES, widget=forms.RadioSelect, label='User Type')
    line1 = forms.CharField(label='Address',widget=forms.TextInput(attrs={
        'placeholder': '58/6 A block Vikas nagar kanpur',}))
  
    city = forms.CharField(max_length=50,widget=forms.TextInput(attrs={
        'placeholder': 'Kanpur',}))
    state = forms.CharField(max_length=50,widget=forms.TextInput(attrs={
        'placeholder': 'U.P',}))
    pincode = forms.CharField(max_length=6,widget=forms.TextInput(attrs={
        'placeholder': '201206',}))

    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "Password and confirm password fields did not match."
            )
    
    def save(self, request):
        user = super(CustomSignUpForm,self).save(request)
        address = Address.objects.create(user=user,line1=self.cleaned_data['line1'], city=self.cleaned_data['city'], state=self.cleaned_data['state'], pincode=self.cleaned_data['pincode'])
      
        profile = Profile.objects.create(user=user, profile_pic=self.cleaned_data['profile_pic'], user_type=self.cleaned_data['user_type'])
        user.profile = profile
        user.address = address
        if profile.user_type == "doctor":
            doctor=Doctor.objects.create(user=user)
            user.doctor = doctor
        elif profile.user_type == "patient":
            patient = Patient.objects.create(user=user)
            user.patient = patient
        #print(user,profile,address,user.profile,user.address)
        user.save()
        return user

Desktop/intership/InterWeb/InterWebApp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
# from django.contrib import messages
# from django.views import View
from.models import Profile
from django.contrib.auth.decorators import login_required
# Create your views here.
class HomeView(TemplateView):
    # model = Profile
    template_name = "interWebApp/home.html"




@login_required
def dashboard(request ):
    profile = request.user.profile 
    user_type = profile.user_type
    
    if user_type == "patient":
        return redirect('InterWebApp:patient_dashboard')
    elif user_type == "doctor":
        return redirect('InterWebApp:doctor_dashboard')
    

def patient_dashboard(request):
    return render(request, 'InterWebApp/patient_dashboard.html')

def doctor_dashboard(request):
    return render(request, 'InterWebApp/doctor_dashboard.html')

Desktop/intership/InterWeb/InterWebApp/templates/InterWebApp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "InterWebApp/navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "InterWebApp/footer.html" %}
    {% include "InterWebApp/scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

Desktop/intership/InterWeb/InterWebApp/templates/InterWebApp/doctor_dashboard.html
{% extends "InterWebApp/base.html" %}




{% block content %}

<main>
  <div class="container">


    <section class="mb-4">
<h1 class="text-center">Welcome to the Patient Dashboard</h1>
      <div class="row wow fadeIn">
        
        <p  class="text-center">Your details are as follows:</p>
        <ul>
          <li>First Name: {{ user.first_name }}</li>
          <li>Last Name: {{ user.last_name }}</li>
          <li>Username: {{ user.username }}</li>
          <li>Email: {{ user.email }}</li>
          <li>Address: {{ user.address.line1 }}, {{ user.address.city }}, {{ user.address.state }}, {{ user.address.pincode }}</li>
        </ul>

      </div>

    </section>



  </div>
</main>


{% endblock %}

Desktop/intership/InterWeb/InterWebApp/templates/InterWebApp/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <!-- <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

       -->
<!--  
      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a> -->

       <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a> 

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>-->
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2023 Copyright:
      <a href="/" target="_blank"> subrat </a>
    </div>
    <!--/.Copyright-->

  </footer>

Desktop/intership/InterWeb/InterWebApp/templates/InterWebApp/home.html
{% extends "InterWebApp/base.html" %}

{% block content %}
<main>
  <div class="container">


    <section class="text-center mb-4">

      <div class="row wow fadeIn">
        <h1>HI! WELCOME  </h1>
        <p class="text-center">I am writing to express my interest in applying for an internship at your organization. As a student pursuing B.tech, I am eager to gain hands-on experience in the field and develop my skills. I believe that an internship at your organization would provide me with the ideal opportunity to do so.

          With Django, I am confident in my ability to contribute to the team at your organization. I am particularly interested in the Web_dev. as it aligns with my career goals and academic background.
          
          I am highly motivated and would bring a strong work ethic and a positive attitude to the internship. I am also a quick learner and am eager to take on new challenges.
          
          I would be grateful for the opportunity to discuss my application further in an interview. Please find my resume attached for your consideration.
          
          Thank you for taking the time to read my application. I look forward to the opportunity to contribute my skills and gain valuable experience at your organization.</p>

      </div>

    </section>



  </div>
</main>

{% endblock content %}

Desktop/intership/InterWeb/InterWebApp/templates/InterWebApp/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">MEDICAL</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link waves-effect" href="{% url 'InterWebApp:dashboard' %}">Dasboard
             
            </a>
          </li>
          {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

Desktop/intership/InterWeb/InterWebApp/templates/InterWebApp/patient_dashboard.html
{% extends "InterWebApp/base.html" %}



{% block content %}

<main>
  <div class="container">


    <section class=" mb-4">
      
      <h1 class="text-center">Welcome to the Patient Dashboard</h1>

      <div class="row wow fadeIn ">
        <p class="text-center"> Your details are as follows:</p>
        <ul>
          <li>First Name: {{ user.first_name }}</li>
          <li>Last Name: {{ user.last_name }}</li>
          <li>Username: {{ user.username }}</li>
          <li>Email: {{ user.email }}</li>
          <li>Address: {{ user.address.line1 }}, {{ user.address.city }}, {{ user.address.state }}, {{ user.address.pincode }}</li>
        </ul>

      </div>

    </section>



  </div>
</main>


{% endblock %}

Desktop/intership/InterWeb/InterWebApp/templates/InterWebApp/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>